from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from datetime import datetime

class ProjectSchema(BaseModel):
    project_id: str = Field(..., description="Unique ID for the project, e.g. timestamp YYYYMMDD_HHMMSS")
    url: str = Field(..., description="YouTube video source URL")
    title: Optional[str] = Field(None, description="Title of the video")
    uploader: Optional[str] = Field(None, description="Uploader of the video")
    duration: Optional[float] = Field(None, description="Duration of the video in seconds")
    status: str = Field("created", description="Current status of the project pipeline")
    video_path: Optional[str] = Field(None, description="Local path to the downloaded video")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class SegmentSchema(BaseModel):
    id: Optional[int] = Field(None, description="Segment ID")
    seek: Optional[int] = Field(None)
    start: float = Field(..., description="Start time in seconds")
    end: float = Field(..., description="End time in seconds")
    text: str = Field(..., description="Text of the segment")
    tokens: Optional[List[int]] = Field(None)
    temperature: Optional[float] = Field(None)
    avg_logprob: Optional[float] = Field(None)
    compression_ratio: Optional[float] = Field(None)
    no_speech_prob: Optional[float] = Field(None)

class TranscriptSchema(BaseModel):
    project_id: str = Field(..., description="Project ID matching the project")
    transcript_text: str = Field(..., description="Concat text of all transcription")
    segments: List[SegmentSchema] = Field(default=[], description="List of granular whisper segment structures")
    created_at: datetime = Field(default_factory=datetime.utcnow)

class ClipSchema(BaseModel):
    project_id: str = Field(..., description="Project ID matching the project")
    clip_index: int = Field(..., description="Index of this clip in the project")
    start: float = Field(..., description="Start timestamp of the clip")
    end: float = Field(..., description="End timestamp of the clip")
    hook: Optional[str] = Field(None, description="Hook text for short-form video")
    reason: Optional[str] = Field(None, description="Reason this highlight is engaging")
    score: Optional[float] = Field(None, description="Engagement score out of 10")
    title: Optional[str] = Field(None, description="Short title generated by metadata agent")
    caption: Optional[str] = Field(None, description="Social caption generated by metadata agent")
    hashtags: Optional[List[str]] = Field(None, description="List of hashtags")
    clip_path: Optional[str] = Field(None, description="File path of cropped landscape clip")
    srt_path: Optional[str] = Field(None, description="File path to the SRT caption file")
    captioned_path: Optional[str] = Field(None, description="File path to clip with burned captions")
    vertical_path: Optional[str] = Field(None, description="File path of the final vertical captioned clip")
    status: str = Field("highlighted", description="Clip status: highlighted, refined, generated, captioned, verticalized")
    created_at: datetime = Field(default_factory=datetime.utcnow)
